### PR TITLE
Add blinky to Max layer

### PR DESCRIPTION
**Pull request by cristeahub**

### CODE REVIEW

**Comment by sigvef** [comment]
rebase please, there has been a lot of changes to the bloom layers

**Comment by cristeahub** [comment]
ping

**Comment by stianjensen** [comment]
needs rebase

**Comment by stianjensen** [comment]
This is one fast moving train!

**Comment by cristeahub** [comment]
wow! last rebase was no change, hope this is just as easy

**Comment by cristeahub** [comment]
it was :+1:

**Comment by cristeahub** [comment]
ping

**Pull request merged**
