### PR TITLE
Interate on the max scene

### PR DESCRIPTION
**Pull request by cristeahub**
Adds some utilities to the textoverlay as well :D

### CODE REVIEW

**Comment by stianjensen** [comment]
Will this move affect the musical timing of the robot and tunnel layer?

**Comment by stianjensen** [comment]
I think at least the start of the tunnel scene should be kept where it is, so that it aligns with the beginning of the chorus

**Comment by cristeahub** [comment]
> I think at least the start of the tunnel scene should be kept where it is, so that it aligns with the beginning of the chorus

Hmm.. the discussion was that the tunnel scene might be a bit long, and that there's a couple of seconds after the tunnel scene. I am sure we will need to revisit this later on

**Comment by stianjensen** [comment]
Sure, we'll probably have to revisit the order and length of all effects in the demo tomorrow

**Comment by cristeahub** [comment]
> Sure, we'll probably have to revisit the order and length of all effects in the demo tomorrow

Ye!

**Pull request merged**
