### PR TITLE
Tunnel update

### PR DESCRIPTION
**Pull request by cristeahub**
Make text clearer and make sure the tunnel scene isn't blinking like crazy.

### CODE REVIEW

**Comment by sigvef** [comment]
I like this scene better with blinking -- it is needed to keep the tunnel colors from becoming non-muddy and ugly.

**Comment by cristeahub** [comment]
> I like this scene better with blinking -- it is needed to make the colors non-muddy and ugly.

I guess we should also change the colors then. The blinking makes the whole scene hard to watch and people can't really see what's going on. This tunes down the blinking, it doesn't remove it.

**Comment by iver56** [comment]
How about a compromise? I like the blinking, but it could perhaps be a little less intense.

**Comment by stianjensen** [comment]
Yeah, we can't remove the blinking altogether

**Comment by cristeahub** [comment]
It's not removed, it's tuned town.

**Comment by iver56** [comment]
Looks fine to me. The blinking is indeed not removed, but just a little less intense.

**Pull request merged**
